### ISSUE TITLE
Great work guys!

### ISSUE THREAD

**Issue by hardcodes** [jryannel/qt5-cadaques#179] opened 2013-12-12 17:42 UTC
I'm misusing this to contact you because I didn't find a contact address after a quick swipe through the book.
Please provide a PDF version of this! It would be great if one could take it on the road, there isn't always an internet connection available.

BR.
Sven

**Comment by jryannel** [comment] 2013-12-12 17:55
Thanks. We currently focus on the HTML only version. But it's completely understandable.

Duplicate of #173 . So I will close this.

**Closed as completed by jryannel** 2013-12-12 17:55 UTC

**Comment by aissat** [comment] 2013-12-13 23:28
It's great job

**Comment by jryannel** [comment] 2014-01-08 06:51
A download version will come this month
